Order methods when exporting csv
Kaligo/rails_admin pull request #5
Opened 2024-01-29 04:54 UTC by jresma

TE: Order methods when exporting csv.

Jira: [[CS] AP > Booking > Export CSV file sequence](https://kaligo.atlassian.net/browse/TE-6279)

2024-01-30 08:14 UTC, jperdiguerra requested changes
@jresma please add spec in `spec/rails_admin/support/csv_converter_spec.rb` 
i.e. keeps headers ordering when schema has `method`

2024-02-01 02:21 UTC, jperdiguerra approved these changes

2024-02-01 02:24 UTC, jresma commented
Specs in local
failed | green
--- | ---
<img width="887" alt="csv - failed" src="https://github.com/Kaligo/rails_admin/assets/4636270/6a5ae931-370c-4efe-ad8e-d1c5dd1b91d3"> | <img width="976" alt="csv - green" src="https://github.com/Kaligo/rails_admin/assets/4636270/1b0a00cf-3812-4162-9bf8-870901d70573">

2024-02-01 10:06 UTC, jresma commented
Hi @playerace please help deploy. 

Tested this on staging and got a go signal from CS
![image](https://github.com/Kaligo/rails_admin/assets/4636270/603938e5-baa6-4d01-bf3d-8455a8f6df9e)

cc: @jperdiguerra

2024-02-01 10:09 UTC, merged